### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by gremory-x** [Ensembl/homebrew-moonshine#1]
Hi,
I just installed genscan, but it seems still not work.

""
$ genscan
-bash: /usr/local/bin/genscan: cannot execute binary file
""

**Comment by andrewyatz** [comment]
Hi. Can you work through the following please

# First Steps
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by thibauthourlier** [comment]
Hi @GRGong ,
I will close this issue as it has been 3 years since you opened it and we haven't heard from you again.
Thanks
